version: '3.8'

services:
  # PostgreSQL 데이터베이스 (개발용)
  postgres-dev:
    image: postgres:15-alpine
    container_name: chatgpt-postgres-dev
    environment:
      POSTGRES_DB: gpt_clone_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3482
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - chatgpt-dev-network

  # Redis 캐시 (개발용)
  redis-dev:
    image: redis:7-alpine
    container_name: chatgpt-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - chatgpt-dev-network
    command: redis-server --appendonly yes

  # Redis Commander (개발용 관리 도구)
  redis-commander-dev:
    image: rediscommander/redis-commander:latest
    container_name: chatgpt-redis-commander-dev
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis-dev
    networks:
      - chatgpt-dev-network

  # FastAPI AI 서비스 (개발용)
  ai-service-dev:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: chatgpt-ai-service-dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./ai:/app
    networks:
      - chatgpt-dev-network
    command: ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  chatgpt-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local 