version: '3.8'

services:
  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: gpt-redis-only
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander (Redis 관리 도구)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: gpt-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - redis-network
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge 